server:
  forward-headers-strategy: framework
  tomcat:
    connection-timeout: 20000

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://orders-service-db:3306/orders
    username: root
    password: gbhre2-fdnji8
  jpa:
    hibernate:
      ddl-auto: none

seata:
  enabled: true
  application-id: orders-service
  tx-service-group: webpos-service-group
  service:
    vgroup-mapping:
      webpos-service-group: seata-server
    grouplist:
      seata-server: seata-server:8091

springdoc:
  api-docs:
    path: /orders-service-api-docs
  cache:
    disabled: true