server:
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://products-service-db:3306/products
    username: root
    password: nlcf8k-15dn2w
  sql:
    init:
      mode: always
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql
  jpa:
    hibernate:
      ddl-auto: none
  cache:
    type: redis
  data:
    redis:
      host: products-cache-server
      port: 6379

seata:
  enabled: true
  application-id: products-service
  tx-service-group: webpos-service-group
  service:
    vgroup-mapping:
      webpos-service-group: seata-server
    grouplist:
      seata-server: seata-server:8091

springdoc:
  api-docs:
    path: /products-service-api-docs
  cache:
    disabled: true
